const $=s=>document.querySelector(s);
const state={token:null,user:null,crops:[],selected:null,capabilities:[],readiness:null};
async function api(path,opt={}){const h={...(opt.headers||{})};if(state.token)h.Authorization=`Bearer ${state.token}`;const r=await fetch(path,{...opt,headers:h});if(!r.ok){let t=await r.text();throw new Error(`${r.status} ${t}`)}return r.json()}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function login(){try{$('#loginError').textContent='';const d=await api('/api/identity/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('#username').value.trim(),password:$('#password').value})});state.token=d.access_token||d.token;if(!state.token)throw new Error('Identity Service không trả access token');await load();$('#loginCard').hidden=true;$('#app').hidden=false}catch(e){$('#loginError').textContent=e.message}}
async function load(){const [me,llm]=await Promise.all([api('/api/router/me/crops'),api('/api/llm/health')]);state.user=me.user;state.crops=me.farm_crops;$('#who').textContent=me.user.display_name;$('#role').textContent=me.user.role;$('#cropCount').textContent=me.unique_crops.length;$('#llmProvider').textContent=llm.provider;$('#llmModel').textContent=llm.model||'deterministic tool router';renderFarms();if(state.crops.length){const preferred=state.crops.find(x=>x.zone_id)||state.crops[0];await selectFarm(preferred)}}
function renderFarms(){const host=$('#farmGrid');host.innerHTML=state.crops.map((x,i)=>`<div class="farm-card" data-i="${i}"><div class="farm-title">${esc(x.farm_name)}</div><div class="crop">${esc(x.source_crop_name)} <span class="meta">→ ${esc(x.crop_key)}</span></div><div class="meta">${x.zone_id?`Khu ${esc(x.zone_code||x.zone_name||x.zone_id)}`:'Hồ sơ cấp vườn'} · mapping ${(Number(x.confidence||0)*100).toFixed(0)}%</div></div>`).join('');host.querySelectorAll('.farm-card').forEach(el=>el.onclick=()=>selectFarm(state.crops[Number(el.dataset.i)],el))}
async function selectFarm(item,el){state.selected=item;document.querySelectorAll('.farm-card').forEach(x=>x.classList.remove('active'));if(el)el.classList.add('active');else{const idx=state.crops.indexOf(item);document.querySelector(`.farm-card[data-i="${idx}"]`)?.classList.add('active')}const q=item.zone_code?`?zone=${encodeURIComponent(item.zone_code)}`:'';const d=await api(`/api/router/farms/${encodeURIComponent(item.farm_id)}/capabilities${q}`);state.capabilities=d.capabilities;state.readiness=d.readiness||null;$('#selectionText').textContent=`${item.farm_name}${item.zone_code?' · khu '+item.zone_code:''} · ${item.source_crop_name} → crop_key=${item.crop_key}`;const status=['ready','experimental','blocked'].map(k=>`<span class="chip ${k}">${k.toUpperCase()}: ${d.counts[k]||0}</span>`);const origins={production:'DỮ LIỆU NEXTFARM',demo:'DỮ LIỆU DEMO',external:'DỮ LIỆU NGOÀI',unavailable:'CHƯA CÓ DỮ LIỆU'};const origin=origins[state.readiness?.origin_kind]||'NGUỒN CHƯA XÁC ĐỊNH';status.push(`<span class="chip ${state.readiness?.origin_kind==='production'?'ready':'experimental'}">${origin} · ${Number(state.readiness?.history_days||0).toFixed(1)} ngày</span>`);$('#statusCounts').innerHTML=status.join('');renderCaps()}
function renderCaps(){const filter=$('#statusFilter').value,term=$('#search').value.trim().toLowerCase();const rows=state.capabilities.filter(x=>(filter==='all'||x.resolved_status===filter)&&(!term||`${x.display_name_vi} ${x.capability_key} ${x.category} ${x.model_family||''}`.toLowerCase().includes(term)));$('#capTable').innerHTML=rows.map(x=>{const req=Array.isArray(x.required_inputs)?x.required_inputs.join(', '):JSON.stringify(x.required_inputs||[]);const reasons=(x.reasons||[]).join(' · ')||x.evidence_note||'';const model=x.model?`${esc(x.model_family||'')}<br><span class="meta">${esc(x.model.model_version||'')}</span>`:esc(x.model_family||'—');const src=x.source_url?`<a class="source" target="_blank" rel="noopener" href="${esc(x.source_url)}">${esc(x.source_title||'Nguồn nghiên cứu')}</a>`:'';return `<tr><td><span class="cap-name">${esc(x.display_name_vi)}</span><br><span class="meta">${esc(x.capability_key)}</span></td><td>${esc(x.category)}</td><td>${esc(x.implementation_type)}</td><td><span class="status ${esc(x.resolved_status)}">${esc(x.resolved_status.toUpperCase())}</span><br><span class="meta">${esc(x.readiness_level||'')}</span></td><td>${model}</td><td>${esc(req)}</td><td>${esc(reasons)}${src}</td></tr>`}).join('')||'<tr><td colspan="7">Không có capability phù hợp bộ lọc.</td></tr>'}
$('#loginBtn').onclick=login;$('#refreshBtn').onclick=load;$('#statusFilter').onchange=renderCaps;$('#search').oninput=renderCaps;$('#password').addEventListener('keydown',e=>{if(e.key==='Enter')login()});
