const $=s=>document.querySelector(s);let catalog=null,lastGridKey='',newCount=0,streamController=null,streamRetry=null,token=sessionStorage.getItem('nf_data_token')||'',user=null;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=(v,d=2)=>v===null||v===undefined?'—':Number(v).toFixed(d);const dt=v=>v?new Date(v).toLocaleString('vi-VN'):'—';
function authHeaders(extra={}){return {...extra,...(token?{Authorization:`Bearer ${token}`}:{})}}
async function json(url,opt={}){const r=await fetch(url,{...opt,headers:authHeaders(opt.headers||{})});let body={};try{body=await r.json()}catch{}if(r.status===401){logout();throw new Error('Phiên đăng nhập đã hết hạn')}if(!r.ok)throw new Error(body.detail||JSON.stringify(body));return body}
async function login(username,password){const x=await json('/api/identity/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});token=x.access_token;user=x.user;sessionStorage.setItem('nf_data_token',token);return x}
function logout(){sessionStorage.removeItem('nf_data_token');token='';user=null;if(streamController)streamController.abort();if(streamRetry)clearTimeout(streamRetry);$('#studioView').hidden=true;$('#loginView').hidden=false}
async function loadCatalog(){catalog=await json('/api/farm/studio/catalog');if(!catalog.farms.length)throw new Error('Tài khoản chưa được cấp quyền đọc vườn nào.');$('#farm').innerHTML=catalog.farms.map(x=>`<option value="${esc(x.farm_id)}">${esc(x.farm_name)}</option>`).join('');$('#metric').innerHTML=catalog.metrics.map(x=>`<option value="${esc(x.metric_type)}">${esc(x.metric_type)} (${esc(x.unit)})</option>`).join('');$('#metric').value='soil_moisture';updateZones()}
function updateZones(){const f=$('#farm').value;$('#zone').innerHTML='<option value="">Tất cả khu</option>'+catalog.zones.filter(x=>x.farm_id===f).map(x=>`<option value="${esc(x.zone_code)}">${esc(x.zone_code)} — ${esc(x.zone_name)}</option>`).join('')}
async function loadStats(){const s=await json('/api/farm/studio/stats?farm_id='+encodeURIComponent($('#farm').value));$('#totalRows').textContent=Number(s.total_rows||0).toLocaleString('vi-VN');$('#latestReading').textContent='Mới nhất: '+dt(s.latest_observed_at);$('#rate').textContent=Number(s.readings_last_minute||0).toLocaleString('vi-VN');$('#latency').textContent=fmt(s.avg_ingest_latency_ms,1)+' ms';$('#models').textContent=s.total_models||0;$('#predictions').textContent=(s.predictions_last_hour||0)+' prediction/giờ của vườn'}
const groupLabels={sensor_readings:'Số đo cảm biến',device_status:'Trạng thái thiết bị',irrigation_schedules:'Lịch tưới',irrigation_runs:'Lịch sử tưới',control_commands:'Nhật ký lệnh',alerts:'Cảnh báo',farm_profile:'Hồ sơ vườn',chat_messages:'Hội thoại chatbot',ingest_attempts:'Tiếp nhận dữ liệu'};
const originLabels={simulated_device_calibrated_v9:'Mô phỏng thiết bị đã hiệu chỉnh',nextfarm_api:'NextFarm API',nextfarm_mqtt:'NextFarm MQTT',manual_import:'Nhập thủ công',partner_api:'API đối tác'};
function ageText(v){if(v===null||v===undefined)return '—';const n=Number(v);if(n<60)return `${n.toFixed(0)} giây`;if(n<3600)return `${(n/60).toFixed(1)} phút`;if(n<86400)return `${(n/3600).toFixed(1)} giờ`;return `${(n/86400).toFixed(1)} ngày`}
function detailText(v){return Object.entries(v||{}).map(([k,n])=>`${k}: ${Number(n).toLocaleString('vi-VN')}`).join(' • ')||'—'}
function statusBadge(v){const labels={fresh:'Tươi',available:'Có dữ liệu',stale:'Trễ',missing:'Thiếu'};return `<span class="badge data-${esc(v)}">${labels[v]||esc(v)}</span>`}
async function loadDataOps(){
  const farm=encodeURIComponent($('#farm').value),days=encodeURIComponent($('#reportDays').value);
  const [groups,report]=await Promise.all([json('/api/farm/studio/data-groups?farm_id='+farm),json(`/api/farm/studio/daily-report?farm_id=${farm}&days=${days}`)]);
  $('#groupBody').innerHTML=groups.items.map(x=>`<tr><td><b>${esc(x.label)}</b><br><small>${esc(x.data_group)}</small></td><td>${Number(x.row_count).toLocaleString('vi-VN')}</td><td>${dt(x.oldest_at)}</td><td>${dt(x.newest_at)}</td><td>${ageText(x.freshness_seconds)}</td><td>${statusBadge(x.status)}</td><td>${esc(detailText(x.details))}</td></tr>`).join('');
  const origins=(groups.sensor_origins||[]).map(x=>`<b>${esc(originLabels[x.data_origin]||x.data_origin)}</b>: ${Number(x.row_count).toLocaleString('vi-VN')} dòng`).join(' • ');
  $('#originSummary').innerHTML=`<strong>Provenance cảm biến:</strong> ${origins||'Chưa có dữ liệu cảm biến.'}<br><small>Dữ liệu mô phỏng và dữ liệu NextFarm thật luôn tách nhãn; bot không được gọi dữ liệu mô phỏng là số đo phần cứng thật.</small>`;
  $('#dailyBody').innerHTML=report.items.map(x=>`<tr><td>${new Date(`${x.report_date}T00:00:00`).toLocaleDateString('vi-VN')}</td><td>${esc(groupLabels[x.data_group]||x.data_group)}</td><td>${Number(x.row_count).toLocaleString('vi-VN')}</td><td>${Number(x.accepted_count).toLocaleString('vi-VN')}</td><td>${Number(x.duplicate_count).toLocaleString('vi-VN')}</td><td>${Number(x.rejected_count).toLocaleString('vi-VN')}</td><td>${Number(x.error_count).toLocaleString('vi-VN')}</td><td>${dt(x.newest_at)}</td></tr>`).join('');
  $('#reportGenerated').textContent=`Truy vấn trực tiếp lúc ${dt(report.generated_at)} • ${report.days} ngày`;
}
async function snapshotReport(){const farm=encodeURIComponent($('#farm').value),days=encodeURIComponent($('#reportDays').value);const x=await json(`/api/farm/studio/daily-report/snapshot?farm_id=${farm}&days=${days}`,{method:'POST'});alert(`Đã chốt ${x.rows} dòng báo cáo vào PostgreSQL.`)}
async function loadGrid(){const q=new URLSearchParams({farm_id:$('#farm').value,minutes:$('#minutes').value,limit:'250'});if($('#zone').value)q.set('zone',$('#zone').value);const d=await json('/api/farm/studio/grid?'+q);const key=d.items[0]?.observed_at||'';if(lastGridKey&&key!==lastGridKey){newCount++;$('#newRows').textContent=newCount+' đợt mới'}lastGridKey=key;$('#gridBody').innerHTML=d.items.map((x,i)=>`<tr class="${i<2?'fresh':''}"><td>${dt(x.observed_at)}</td><td>${esc(x.farm_name)}</td><td>${esc(x.zone_code||'—')}</td><td>${fmt(x.soil_moisture)}</td><td>${fmt(x.air_humidity)}</td><td>${fmt(x.temperature)}</td><td>${fmt(x.ec,3)}</td><td>${fmt(x.ph,3)}</td><td>${fmt(x.flow_rate)}</td><td>${esc(x.quality||'—')}</td></tr>`).join('')}
function drawChart(items){const c=$('#seriesChart'),ctx=c.getContext('2d'),w=c.width,h=c.height,p=55;ctx.clearRect(0,0,w,h);if(!items.length){ctx.fillText('Chưa có dữ liệu',p,p);return}const vals=items.map(x=>x.avg_value),mn=Math.min(...vals),mx=Math.max(...vals),range=Math.max(.001,mx-mn);ctx.strokeStyle='#d7e5de';ctx.lineWidth=1;for(let i=0;i<6;i++){const y=p+(h-2*p)*i/5;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke();ctx.fillStyle='#60736a';ctx.fillText((mx-range*i/5).toFixed(2),8,y+4)}ctx.strokeStyle='#16794f';ctx.lineWidth=3;ctx.beginPath();items.forEach((x,i)=>{const X=p+(w-2*p)*i/Math.max(1,items.length-1),Y=p+(h-2*p)*(mx-x.avg_value)/range;i?ctx.lineTo(X,Y):ctx.moveTo(X,Y)});ctx.stroke();ctx.fillStyle='#10251c';ctx.fillText(dt(items[0].bucket),p,h-15);ctx.fillText(dt(items.at(-1).bucket),w-p-160,h-15);$('#chartLegend').textContent=`Min ${mn.toFixed(3)} • Max ${mx.toFixed(3)} • ${items.length} bucket`}
async function loadSeries(){const q=new URLSearchParams({farm_id:$('#farm').value,metric:$('#metric').value,hours:String(Math.max(1,Math.ceil(Number($('#minutes').value)/60))),bucket_seconds:$('#bucket').value});if($('#zone').value)q.set('zone',$('#zone').value);drawChart((await json('/api/farm/studio/series?'+q)).items)}
async function evaluate(){const q=new URLSearchParams({farm_id:$('#farm').value,metric:$('#metric').value,minutes:$('#minutes').value,expected_interval_seconds:'2'});if($('#zone').value)q.set('zone',$('#zone').value);const e=await json('/api/farm/studio/evaluate?'+q),s=e.statistics,d=e.data_quality,t=e.threshold_compliance;$('#evalCards').innerHTML=`<article><small>Trung bình</small><b>${fmt(s.avg_value,3)}</b><small>Min ${fmt(s.min_value,2)} / Max ${fmt(s.max_value,2)}</small></article><article><small>Xu hướng mỗi giờ</small><b>${fmt(s.slope_per_hour,3)}</b><small>regr_slope</small></article><article><small>Độ đầy đủ</small><b>${fmt(d.completeness*100,1)}%</b><small>${d.actual_samples}/${d.expected_samples} mẫu</small></article><article><small>Trong ngưỡng</small><b>${t.available?fmt(t.inside_percent,1)+'%':'N/A'}</b><small>${t.available?'Dưới '+t.below_seconds+'s / Trên '+t.above_seconds+'s':'Chưa cấu hình ngưỡng'}</small></article><article><small>Uptime thiết bị</small><b>${fmt(e.device_uptime.online_percent,1)}%</b><small>${e.device_uptime.samples} trạng thái</small></article><article><small>Ca tưới thành công</small><b>${e.irrigation.success_percent===null?'N/A':fmt(e.irrigation.success_percent,1)+'%'}</b><small>${e.irrigation.runs} ca</small></article><article><small>Đáp ứng sau tưới</small><b>${e.irrigation.moisture_response.available?fmt(e.irrigation.moisture_response.delta,2):'N/A'}</b><small>Δ độ ẩm trước/sau</small></article><article><small>FAO-56 ETo</small><b>${e.eto_readiness.ready?'Sẵn sàng':'Chưa đủ'}</b><small>Thiếu ${esc(e.eto_readiness.missing.join(', '))}</small></article>`;$('#evalJson').textContent=JSON.stringify(e,null,2)}
async function loadMqtt(){const d=await json('/api/farm/studio/ingest-events?farm_id='+encodeURIComponent($('#farm').value));$('#mqttBody').innerHTML=d.items.map(x=>`<tr><td>${dt(x.received_at)}</td><td>${esc(x.mqtt_topic)}</td><td>${esc((x.packet_id||'').slice(0,12))}…</td><td>${esc(x.message_type)}</td><td>${x.inserted_readings}</td><td>${fmt(x.insert_latency_ms,1)} ms</td><td>${esc(x.status)}</td></tr>`).join('')}
async function refreshAll(){try{await Promise.all([loadStats(),loadGrid(),loadSeries(),loadMqtt()]);$('#connectionText').textContent='Realtime đang hoạt động'}catch(e){$('#connectionText').textContent='Lỗi: '+e.message}}
async function setupStream(){
  if(streamController)streamController.abort();if(streamRetry)clearTimeout(streamRetry);
  streamController=new AbortController();const q=new URLSearchParams({farm_id:$('#farm').value});
  try{
    const r=await fetch('/api/farm/studio/stream?'+q,{headers:authHeaders(),signal:streamController.signal});
    if(!r.ok)throw new Error('SSE '+r.status);const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';
    while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const blocks=buffer.split('\n\n');buffer=blocks.pop()||'';for(const block of blocks){if(block.includes('event: readings')){loadGrid();loadStats();loadSeries()}}}
  }catch(e){if(e.name!=='AbortError'&&token){$('#connectionText').textContent='Đang kết nối lại SSE có xác thực…';streamRetry=setTimeout(setupStream,2000)}}
}
async function exportCsv(){const q=new URLSearchParams({farm_id:$('#farm').value,minutes:$('#minutes').value});if($('#zone').value)q.set('zone',$('#zone').value);const r=await fetch('/api/farm/studio/export.csv?'+q,{headers:authHeaders()});if(!r.ok)throw new Error('Không xuất được CSV');const blob=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`nextfarm-${$('#farm').value}.csv`;a.click();URL.revokeObjectURL(a.href)}
async function enter(){if(!user)user=await json('/api/identity/auth/me');$('#loginView').hidden=true;$('#studioView').hidden=false;window.scrollTo(0,0);$('#userText').textContent=`${user.display_name} • ${user.role==='technician'?'Kỹ thuật viên':'Nông dân'}`;$('#snapshotReport').hidden=user.role!=='technician';await loadCatalog();await refreshAll();setupStream()}
document.addEventListener('DOMContentLoaded',async()=>{$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';const btn=$('#loginBtn'),label=btn.querySelector('span');btn.disabled=true;label.textContent='Đang xác thực...';try{await login($('#username').value.trim(),$('#password').value);await enter()}catch(err){$('#loginError').textContent=err.message}finally{btn.disabled=false;label.textContent='Đăng nhập'}};$('#logout').onclick=logout;if(token){try{await enter()}catch{logout()}}setInterval(()=>{if(token&&!$('#studioView').hidden){loadStats();loadMqtt();if($('#dataops').classList.contains('active'))loadDataOps()}},5000);$('#farm').addEventListener('change',()=>{updateZones();newCount=0;setupStream();refreshAll();if($('#dataops').classList.contains('active'))loadDataOps()});$('#refresh').addEventListener('click',refreshAll);$('#evaluate').addEventListener('click',evaluate);$('#export').addEventListener('click',()=>exportCsv().catch(e=>alert(e.message)));$('#reportDays').addEventListener('change',()=>loadDataOps().catch(e=>alert(e.message)));$('#snapshotReport').addEventListener('click',()=>snapshotReport().catch(e=>alert(e.message)));document.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tabs button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');if(b.dataset.tab==='evaluation')evaluate();if(b.dataset.tab==='dataops')loadDataOps().catch(e=>alert(e.message))}))});
