const $=s=>document.querySelector(s);let selected=null,token=sessionStorage.getItem('nf_knowledge_token')||'',user=null;const dt=v=>v?new Date(v).toLocaleString('vi-VN'):'—';
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const safeUrl=v=>{try{const u=new URL(String(v));return u.protocol==='https:'?u.href:'#'}catch{return '#'}};
function authHeaders(extra={}){return {...extra,...(token?{Authorization:`Bearer ${token}`}:{})}}
async function j(url,opt={}){const r=await fetch(url,{...opt,headers:authHeaders(opt.headers||{})});let b={};try{b=await r.json()}catch{}if(r.status===401){logout();throw new Error('Phiên đăng nhập đã hết hạn')}if(!r.ok)throw new Error(b.detail||JSON.stringify(b));return b}
async function login(username,password){const x=await j('/api/identity/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});if(x.user.role!=='technician')throw new Error('Tài khoản này không phải kỹ thuật viên.');token=x.access_token;user=x.user;sessionStorage.setItem('nf_knowledge_token',token)}
function logout(){sessionStorage.removeItem('nf_knowledge_token');token='';user=null;selected=null;$('#studioView').hidden=true;$('#loginView').hidden=false}
async function stats(){const x=await j('/api/knowledge/studio/stats'),g=x.production_gate||{};$('#stats').innerHTML=`<article><small>Nguồn</small><b>${Number(x.sources)}</b></article><article><small>Tài liệu</small><b>${Number(x.total)}</b></article><article><small>Đã duyệt</small><b>${Number(x.approved)}</b></article><article><small>Bản nháp</small><b>${Number(x.drafts)}</b></article><article><small>Chunks / lượt hỏi</small><b>${Number(x.chunks)}</b><small>${Number(x.queries)} truy xuất</small></article><article><small>Production gate</small><b>${g.ready?'ĐẠT':'CHƯA ĐẠT'}</b><small>${esc((g.gaps||[]).join(' • ')||'Đã đủ ngưỡng tối thiểu')}</small></article>`}
async function docs(){const d=await j('/api/knowledge/studio/documents?approved='+encodeURIComponent($('#approved').value));$('#documents').innerHTML=d.items.map(x=>`<div class="doc" data-id="${esc(x.document_id)}"><strong>${esc(x.title)}</strong><small>${esc(x.source_name)} • Tier ${Number(x.trust_tier)} • ${Number(x.chunk_count)} mục</small><br><span class="tag ${x.approved?'':'draft'}">${x.approved?'Đã duyệt':'Bản nháp'}</span></div>`).join('');document.querySelectorAll('.doc').forEach(el=>el.addEventListener('click',()=>openDoc(el.dataset.id)))}
async function openDoc(id){selected=await j('/api/knowledge/studio/documents/'+encodeURIComponent(id));document.querySelectorAll('.doc').forEach(x=>x.classList.toggle('active',x.dataset.id===id));$('#approveDoc').disabled=selected.approved;const source=safeUrl(selected.source_url);$('#documentDetail').innerHTML=`<h3>${esc(selected.title)}</h3><div class="source-card"><b>${esc(selected.source_name)}</b><br><a href="${esc(source)}" target="_blank" rel="noopener noreferrer">${esc(selected.source_url)}</a><br><small>Trust tier ${Number(selected.trust_tier)} • ${selected.approved?'đã duyệt':'chưa duyệt'} • cập nhật ${dt(selected.updated_at)}</small></div>${selected.chunks.map((c,i)=>`<article class="chunk"><small>[Mục ${i+1}] ${esc(c.section_path||'Nội dung chính')}</small><h3>${esc(c.heading||selected.title)}</h3><p>${esc(c.content_vi)}</p><small>Locator: ${esc(c.source_locator||selected.source_url)}</small></article>`).join('')}`}
async function ask(){const q=$('#question').value.trim(),x=await j('/api/knowledge/studio/answer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:q,limit:4})});$('#guard').className='guard'+(x.answerable?'':' blocked');$('#guard').textContent=x.answerable?`Truth Guard: evidence-only • confidence ${x.confidence} • không cho claim không nguồn`:'Truth Guard đã chặn: chưa đủ tài liệu được duyệt';$('#answer').textContent=x.answer;$('#citations').innerHTML=x.citations.map(c=>{const u=safeUrl(c.source_url);return `<div class="citation"><b>[${esc(c.citation_id)}] ${esc(c.title)}</b><br><span>${esc(c.section)}</span><br><a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(c.source_name)} — ${esc(c.source_url)}</a><br><small>Trust tier ${Number(c.trust_tier)} • score ${Number(c.score)}</small></div>`}).join('')}
async function ingest(){try{$('#ingestResult').textContent='Đang tải và tách tài liệu…';const x=await j('/api/knowledge/studio/ingest-url',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:$('#url').value,source_name:$('#sourceName').value||null,category:$('#category').value})});$('#ingestResult').textContent=JSON.stringify(x,null,2);await Promise.all([stats(),docs()]);await openDoc(x.document_id)}catch(e){$('#ingestResult').textContent=e.message}}
async function approve(){if(!selected)return;try{await j('/api/knowledge/admin/documents/'+encodeURIComponent(selected.document_id)+'/approve',{method:'POST'});await Promise.all([stats(),docs()]);await openDoc(selected.document_id)}catch(e){alert(e.message)}}
async function enter(){if(!user)user=await j('/api/identity/auth/me');if(user.role!=='technician')throw new Error('Chỉ kỹ thuật viên được mở Knowledge Studio.');$('#loginView').hidden=true;$('#studioView').hidden=false;window.scrollTo(0,0);$('#userText').textContent=user.display_name;await Promise.all([stats(),docs()]);await ask()}
document.addEventListener('DOMContentLoaded',async()=>{$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';const btn=$('#loginBtn'),label=btn.querySelector('span');btn.disabled=true;label.textContent='Đang xác thực...';try{await login($('#username').value.trim(),$('#password').value);await enter()}catch(err){$('#loginError').textContent=err.message}finally{btn.disabled=false;label.textContent='Đăng nhập kỹ thuật viên'}};$('#logout').onclick=logout;$('#reload').onclick=docs;$('#approved').onchange=docs;$('#ask').onclick=ask;$('#question').addEventListener('keydown',e=>{if(e.key==='Enter')ask()});$('#ingest').onclick=ingest;$('#approveDoc').onclick=approve;if(token){try{await enter()}catch(err){logout();$('#loginError').textContent=err.message}}});
