const $=s=>document.querySelector(s), state={token:sessionStorage.getItem('nf_device_token'),user:null,devices:[],tab:'chat',device:null};
const groups={sensor_readings:'Số đo cảm biến',device_status:'Trạng thái thiết bị',irrigation_schedules:'Lịch tưới',irrigation_runs:'Lịch sử tưới',control_commands:'Nhật ký lệnh',alerts:'Cảnh báo',device_profile:'Hồ sơ khách hàng và tủ'};
const esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function error(e){$('#error').textContent=e?.message||String(e||'');}
async function api(path,options={}){const r=await fetch(path,{...options,headers:{...(options.headers||{}),...(state.token?{Authorization:`Bearer ${state.token}`}:{})}});const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:data.detail?.message||`Lỗi ${r.status}`);return data;}
function table(items){if(!items.length)return '<p>Chưa có bản ghi.</p>';const keys=[...new Set(items.flatMap(x=>Object.keys(x)))];return '<table><thead><tr>'+keys.map(k=>`<th>${esc(k)}</th>`).join('')+'</tr></thead><tbody>'+items.map(r=>'<tr>'+keys.map(k=>`<td>${esc(typeof r[k]==='object'?JSON.stringify(r[k]):r[k])}</td>`).join('')+'</tr>').join('')+'</tbody></table>';}
function bubble(text,user=false,id=null){const div=document.createElement('div');div.className='bubble'+(user?' user':'');const p=document.createElement('p');p.textContent=text;div.append(p);if(id){const row=document.createElement('div');for(const [title,useful] of [['Hữu ích',true],['Chưa đúng ý',false]]){const b=document.createElement('button');b.textContent=title;b.onclick=async()=>{try{await api('/api/chatbot/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:id,useful})});row.textContent='Đã ghi nhận. Phản hồi không tự động đưa vào train.';}catch(e){error(e)}};row.append(b)}div.append(row)}$('#messages').append(div);$('#messages').scrollTop=$('#messages').scrollHeight;}
async function enter(){const r=await api('/api/farm/devices');state.devices=r.items;state.user=r.user;$('#login').hidden=true;$('#workspace').hidden=false;$('#logout').hidden=false;$('#welcome').textContent=state.user.displayName||state.user.display_name;const tech=state.user.role==='technician';$('#role').textContent=tech?'Duyệt tri thức và xem dữ liệu khách hàng':'Nông dân · Chọn tủ trước khi trò chuyện';$('#knowledge').hidden=!tech;document.querySelector('[data-tab="chat"]').hidden=tech;state.tab=tech?'data':(document.body.dataset.startTab||'chat');$('#device').innerHTML='<option value="">Chọn một tủ</option>'+state.devices.map(x=>`<option value="${esc(x.device_id)}">${esc(x.device_name)} · ${esc(x.customer_id)}</option>`).join('');await showTab(state.tab);}
async function showTab(name){state.tab=name;for(const k of ['chat','data','models','capabilities'])$('#'+k).hidden=k!==name;if(!state.device)return;error('');try{if(name==='data')await loadData();if(name==='models'){const r=await api(`/api/analytics/devices/${state.device}/models`);$('#models').innerHTML=`<h2>10 model dự báo</h2><p>Chưa có model được nghiệm thu để phát hành dự báo. Trạng thái thu dữ liệu: ${esc(r.collection?.status)}. Đã thu ${Number(r.collection?.devices?.[state.device]?.elapsed_received_hours||0).toFixed(2)}/72 giờ theo thời gian server nhận. Số đo hiện tại vẫn xem và hỏi qua API dữ liệu.</p><div class="scroll">${table((r.models||[]).map(m=>({Model:m.title,Trạng_thái:m.status,Thuật_toán:m.algorithm,Lý_do:(m.gate_reasons||[]).join('; ')})))}</div>`;}if(name==='capabilities'){const r=await api(`/api/router/devices/${state.device}/capabilities`);$('#capabilities').innerHTML=`<h2>32 năng lực theo tủ</h2><p>${esc(r.note)}</p><div class="scroll">${table(r.items.map(x=>({Tên:x.title,Loại:x.kind,Trạng_thái:x.status,Phạm_vi:x.scope,Lý_do:x.reason.join('; ')})))}</div>`;}}catch(e){error(e)}}
async function loadData(){const selected=state.device,group=$('#group').value,period=$('#period').value;const r=await api(`/api/farm/devices/${selected}/data?group=${group}&period=${period}`);if(selected!==state.device||group!==$('#group').value||period!==$('#period').value)return;$('#dataInfo').textContent=`${r.count} bản ghi · khách hàng ${r.customer_id} · tủ ${r.device_id} · nguồn ${r.source}`;$('#dataTable').innerHTML=table(r.items);}
$('#group').innerHTML=Object.entries(groups).map(([key,title])=>`<option value="${key}">${title}</option>`).join('');
$('#loginForm').onsubmit=async e=>{e.preventDefault();error('');try{const r=await api('/api/identity/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('#username').value,password:$('#password').value})});state.token=r.access_token;sessionStorage.setItem('nf_device_token',state.token);$('#password').value='';await enter();}catch(e){error(e)}};
$('#logout').onclick=()=>{sessionStorage.removeItem('nf_device_token');location.reload()};
$('#device').onchange=async()=>{state.device=$('#device').value;$('#messages').textContent='';$('#dataTable').textContent='';$('#models').textContent='';$('#capabilities').textContent='';$('#dataInfo').textContent='';if(state.device&&state.user.role==='farmer'){try{const h=await api(`/api/chatbot/conversations/current/messages?device_id=${state.device}`);for(const m of h.items){bubble(m.question,true);bubble(m.answer,false,m.id)}}catch(e){error(e)}}await showTab(state.tab)};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{$('#message').value=b.dataset.q;$('#chatForm').requestSubmit()});
$('#chatForm').onsubmit=async e=>{e.preventDefault();if(!state.device)return error('Hãy chọn một tủ trước khi hỏi.');const message=$('#message').value.trim();if(!message)return;$('#send').disabled=true;$('#device').disabled=true;bubble(message,true);$('#message').value='';try{const r=await api('/api/chatbot/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({device_id:state.device,message})});bubble(r.answer,false,r.chat_id)}catch(e){error(e)}finally{$('#send').disabled=false;$('#device').disabled=false}};
$('#reload').onclick=()=>state.device?loadData().catch(error):error('Chọn tủ trước.');
$('#export').onclick=async()=>{if(!state.device)return error('Chọn tủ trước.');try{const r=await fetch(`/api/farm/devices/${state.device}/export.csv?group=${$('#group').value}&period=${$('#period').value}`,{headers:{Authorization:`Bearer ${state.token}`}});if(!r.ok)throw Error('Không xuất được CSV');const u=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=u;a.download=`${state.device}_${$('#group').value}.csv`;a.click();URL.revokeObjectURL(u)}catch(e){error(e)}};
if(state.token)enter().catch(e=>{sessionStorage.removeItem('nf_device_token');state.token=null;error(e)});

let devicePolling=false;setInterval(async()=>{if(devicePolling||document.hidden||!state.device||state.tab!=='data'||!['device_status','alerts'].includes($('#group').value))return;devicePolling=true;try{await loadData()}catch(e){error(e)}finally{devicePolling=false}},5000);
