persistence true
persistence_location /mosquitto/data/
autosave_interval 60

listener 1883
protocol mqtt
allow_anonymous false
password_file /mosquitto/secrets/passwords
acl_file /mosquitto/config/acl.prod

log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true
